-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 11:54:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PruebaEmpleados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PruebaEmpleados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PruebaEmpleados` DEFAULT CHARACTER SET utf8 ;
USE `PruebaEmpleados` ;

-- -----------------------------------------------------
-- Table `PruebaEmpleados`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaEmpleados`.`Empleados` (
  `DPI` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `No_Seguro` VARCHAR(45) NOT NULL,
  `Telefono` INT(8) NOT NULL,
  PRIMARY KEY (`DPI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaEmpleados`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaEmpleados`.`Departamentos` (
  `Codigo_Departamento` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaEmpleados`.`Contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaEmpleados`.`Contratos` (
  `Codigo_Contratos` INT NOT NULL AUTO_INCREMENT,
  `DPI` INT GENERATED ALWAYS AS () VIRTUAL,
  `Codigo_Departamento` INT NOT NULL,
  `Puesto` VARCHAR(40) NOT NULL,
  `Jerarquia` VARCHAR(40) NOT NULL,
  `Sueldo` DECIMAL(25) NOT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `Fecha_Aumento` DATE NOT NULL,
  `Fecha_Baja` DATE NOT NULL,
  PRIMARY KEY (`Codigo_Contratos`),
  INDEX `fk_Contratos_Empleados_idx` (`DPI` ASC) VISIBLE,
  INDEX `fk_Contratos_Departamentos1_idx` (`Codigo_Departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Contratos_Empleados`
    FOREIGN KEY (`DPI`)
    REFERENCES `PruebaEmpleados`.`Empleados` (`DPI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contratos_Departamentos1`
    FOREIGN KEY (`Codigo_Departamento`)
    REFERENCES `PruebaEmpleados`.`Departamentos` (`Codigo_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
