USE PruebaEmpleados
/*Creacion del Procedimineto Almcenados De Empleados*/
DELIMITER $$
CREATE PROCEDURE `SP_INGRESAR_EMPLEADO` (IN DPI INT(10), IN NOMBRE VARCHAR(45), IN APELLIDOS VARCHAR(45),IN DIRECCION VARCHAR(45), IN SEGURO INT(10), IN TELEFONO INT(11))
BEGIN
	INSERT INTO empleados VALUES(DPI,NOMBRE, APELLIDOS, DIRECCION, SEGURO, TELEFONO);
END $$

CALL SP_INGRESAR_CLIENTES (715163,'Rick','Grimes','Ciudad','545463','45089541')

DELIMITER $$
CREATE PROCEDURE `SP_MODIFICAR_EMPLEADO` (IN Codigo INT, IN NOMBRE VARCHAR(45), IN APELLIDOS VARCHAR(45),
										  IN DIRECCION VARCHAR(45), IN SEGURO INT, IN TELEFONO INT)
BEGIN
	UPDATE empleados SET Nombre=NOMBRE ,Apellidos=APELLIDOS,Direccion=DIRECCION,No_Seguro=SEGURO, Telefono=TELEFONO Where DPI=Codigo;
END $$
DELIMITER ;

CALL SP_MODIFICAR_EMPLEADO ('715163','Rick','Grimes','Ciudad','421889','789412')

DELIMITER $$
CREATE PROCEDURE `SP_ELIMINAR_EMPLEADO` (IN Codigo INT)
BEGIN
	DELETE FROM empleados Where DPI=Codigo;
END $$
DELIMITER ;

CALL SP_ELIMINAR_EMPLEADO('12516')

/*Creacion De Procedimiento Almacenados Para Departamentos*/
DELIMITER $$
CREATE PROCEDURE `SP_INGRESAR_DEPARTAMENTO` (IN CODIGO INT, IN NOMBRE VARCHAR(45))
BEGIN
	INSERT INTO departamentos VALUES(CODIGO,NOMBRE);
END $$

DELIMITER ;

CALL SP_INGRESAR_DEPARTAMENTO ('45642','RRHH')

DELIMITER $$
CREATE PROCEDURE `SP_MODIFICAR_DEPARTAMENTO` (IN CODIGO INT, IN DEPA VARCHAR(45))
BEGIN
	UPDATE departamentos SET Nombre=DEPA WHERE Codigo_Departamento=CODIGO;
END $$

DELIMITER ;

CALL SP_MODIFICAR_DEPARTAMENTO('4548','RRHH')

DELIMITER $$
CREATE PROCEDURE `SP_ELIMINAR_DEPARTAMENTO` (IN CODIGO INT)
BEGIN
	DELETE FROM departamentos WHERE Codigo_Departamento=CODIGO;
END $$
DELIMITER ;

CALL SP_ELIMINAR_DEPARTAMENTO (45642)
/*Creacion De Procedimientos Almacenados Para Contrato*/
DELIMITER $$
CREATE PROCEDURE `SP_INGRESAR_CONTRATO` (IN CODIGO INT, IN DPI INT, IN CODIGODEPAR INT, IN PUESTO VARCHAR(40),
										 IN JERAR VARCHAR(25), IN SUELDO DECIMAL, IN FECHA_INGRESO DATE,
                                         IN FECHA_AUMENTO DATE, IN FECHA_BAJA DATE)
BEGIN
	INSERT INTO contratos VALUES(CODIGO,DPI, CODIGODEPAR,PUESTO, JERAR, SUELDO, FECHA_INGRESO, FECHA_AUMENTO, FECHA_BAJA);
END $$

DELIMITER $$
CREATE PROCEDURE `SP_MODIFICAR_CONTRATO` (IN CODIGO INT, IN DpiE INT, IN CODIGODEPAR INT, IN Pues VARCHAR(40),
										 IN JERAR VARCHAR(25), IN SUEL DECIMAL, IN FINGRESO DATE,
                                         IN FAUMENTO DATE, IN FBAJA DATE)
BEGIN
	UPDATE contratos SET DPI=DpiE, Codigo_Departamento=CODIGODEPAR,Puesto=Pues, Jerarquia=JERAR, Sueldo=SUEL, Fecha_Ingreso=FINGRESO, Fecha_Aumento=FAUMENTO, Fecha_Baja=FBAJA WHERE Codigo_Contratos=CODIGO;
END $$

DELIMITER ;

CALL SP_MODIFICAR_CONTRATO ('474321','715163','4548','Asistente Financiero','Invertir','3500','2017-06-17','2020-02-04','2021-03-02')

CALL SP_INGRESAR_CONTRATO ('444315','54387','4531','Asistente','Finanzas','5000.00','2017-02-13','2017-03-17',curdate())

DELIMITER $$
CREATE PROCEDURE `SP_ELIMINAR_CONTRATO` (IN CODIGO INT)
BEGIN
	DELETE FROM contratos WHERE Codigo_Contratos=CODIGO;
END $$

DELIMITER ;

CALL SP_ELIMINAR_CONTRATO ('3987')